# Generated by Django 4.1.7 on 2023-03-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0003_alter_ghuser_html_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
