# Generated by Django 4.1.7 on 2023-03-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0002_rename_owner_id_repo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghuser',
            name='html_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
